<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<title>MANA-VIZITKARTE</title>';
echo '<link href="style.css" rel="stylesheet" type="text/css" />';
echo '</head>';
echo '';
echo '<body>';
echo '<nav>';
echo '<div class="menu">';
echo '<ul>';
echo '<li id="index.html"><a href="">Home</a></li>';
echo '<li><a href="par_mani.html">Par mani</a></li>';
echo '<li><a href="kontaktinformacija.html">Kontaktinformācija</a></li>';
echo '<li><a href="projekti.html">Projekti</a></li>';
echo '<li><a href="sazina.html">Tiešā saziņa</a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '';
echo '<div class="img"></div>';
echo '';
echo '<!--Līdz šai daļai tiek izmantots katrā lapā -->';
echo '';
echo '<div class="center">';
echo '<div class="title">Šī ir mājaslapa kurā es esmu nedaudz par sevi pastāstījis</div>';
echo '<br>';
echo '<br>';
echo '<div class="sub_title">Pārvietojoties pa lapu var redzēt visdažādāko informāciju</div>';
echo '<div class="btns">';
echo '<button>';
echo '<a href="par_mani.html">Par mani</a>';
echo '</button>';
echo '';
echo '<button>';
echo '<a href="kontaktinformacija.html">Kontaktinformācija</a>';
echo '</button>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<script src="script.js"></script>';
echo '<script src="https://replit.com/public/js/replit-badge.js" theme="blue" defer></script>';
echo '</body>';
echo '';
echo '</html>';
echo '';
?>